name: pipeline-manual-run to run test cases manually

on:
  workflow_dispatch:

jobs:
  run-test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out the repo
        uses: actions/checkout@v4

      - name: listing the files before running
        run: find .

      - name: Build the project (compile and install)
        run: mvn clean install -DskipTests

      - name: Running the test cases
        continue-on-error: true
        run: mvn clean test -Dsuite=vendor-portal.xml

      - name: Printing the Test execution status
        if: always()                                           # adding always() since this step will run always even if test cases run fail
        continue-on-error: true
        run: cat target/test-output/testng-report/TestSuite.txt

      - name: Publishing the Test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports-upload-extentReport
          path: target/test-output/extent-Report
          retention-days: 100                                 # for 100 days the report will persist after that it will be deleted